const state={files:[],currentScreen:"home"};
const screenTitles={home:"Home","new-analysis":"New Analysis",validation:"Statement Validation",history:"History",settings:"Settings"};
const elements={pdfInput:document.getElementById("pdfInput"),dropZone:document.getElementById("dropZone"),statementQueue:document.getElementById("statementQueue"),emptyQueue:document.getElementById("emptyQueue"),statementCount:document.getElementById("statementCount"),totalSize:document.getElementById("totalSize"),clearQueue:document.getElementById("clearQueue"),continueButton:document.getElementById("continueButton"),fileStatus:document.getElementById("fileStatus"),validationFiles:document.getElementById("validationFiles"),validationLoaded:document.getElementById("validationLoaded"),screenTitle:document.getElementById("screenTitle")};
function navigate(screenId){const target=document.getElementById(screenId);if(!target)return;document.querySelectorAll(".screen").forEach(s=>s.classList.toggle("active",s.id===screenId));document.querySelectorAll(".bottom-nav button").forEach(b=>b.classList.toggle("active",b.dataset.screen===screenId));state.currentScreen=screenId;elements.screenTitle.textContent=screenTitles[screenId]||"ClearCost AI";if(screenId==="validation")renderValidationFiles();window.scrollTo({top:0,behavior:"smooth"});}
function formatBytes(bytes){if(bytes===0)return"0 KB";const units=["B","KB","MB","GB"];const i=Math.min(Math.floor(Math.log(bytes)/Math.log(1024)),units.length-1);const value=bytes/Math.pow(1024,i);return`${value.toFixed(i===0?0:2)} ${units[i]}`;}
function fileKey(file){return`${file.name}-${file.size}-${file.lastModified}`;}
function addFiles(fileList){const incoming=Array.from(fileList).filter(file=>file.type==="application/pdf"||file.name.toLowerCase().endsWith(".pdf"));incoming.forEach(file=>{if(!state.files.some(existing=>fileKey(existing)===fileKey(file)))state.files.push(file);});renderQueue();}
function removeFile(key){state.files=state.files.filter(file=>fileKey(file)!==key);renderQueue();}
function clearQueue(){state.files=[];elements.pdfInput.value="";renderQueue();}
function renderQueue(){elements.statementQueue.innerHTML="";state.files.forEach(file=>{const card=document.createElement("article");card.className="file-card";const details=document.createElement("div");const name=document.createElement("strong");const metadata=document.createElement("small");name.textContent=file.name;metadata.textContent=`${formatBytes(file.size)} · Waiting for statement processing`;details.append(name,metadata);const removeButton=document.createElement("button");removeButton.type="button";removeButton.className="remove-file";removeButton.setAttribute("aria-label",`Remove ${file.name}`);removeButton.textContent="×";removeButton.addEventListener("click",()=>removeFile(fileKey(file)));card.append(details,removeButton);elements.statementQueue.append(card);});const totalBytes=state.files.reduce((sum,file)=>sum+file.size,0);elements.statementCount.textContent=String(state.files.length);elements.totalSize.textContent=formatBytes(totalBytes);elements.emptyQueue.hidden=state.files.length>0;elements.clearQueue.disabled=state.files.length===0;elements.continueButton.disabled=state.files.length===0;elements.fileStatus.textContent=state.files.length>0?`${state.files.length} PDF file${state.files.length===1?"":"s"} loaded`:"Waiting for statement selection";}
function renderValidationFiles(){elements.validationFiles.innerHTML="";elements.validationLoaded.textContent=String(state.files.length);state.files.forEach(file=>{const card=document.createElement("article");card.className="file-card";const details=document.createElement("div");const name=document.createElement("strong");const meta=document.createElement("small");name.textContent=file.name;meta.textContent=`${formatBytes(file.size)} · File loaded`;details.append(name,meta);const check=document.createElement("span");check.setAttribute("aria-hidden","true");check.textContent="✓";card.append(details,check);elements.validationFiles.append(card);});}
document.addEventListener("click",event=>{const button=event.target.closest("[data-screen]");if(button)navigate(button.dataset.screen);});
elements.pdfInput.addEventListener("change",event=>addFiles(event.target.files));elements.clearQueue.addEventListener("click",clearQueue);["dragenter","dragover"].forEach(name=>elements.dropZone.addEventListener(name,event=>{event.preventDefault();elements.dropZone.classList.add("dragover");}));["dragleave","drop"].forEach(name=>elements.dropZone.addEventListener(name,event=>{event.preventDefault();elements.dropZone.classList.remove("dragover");}));elements.dropZone.addEventListener("drop",event=>addFiles(event.dataTransfer.files));renderQueue();navigate("home");
