import * as pdfjsLib from 'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs';
import {stableHash,extractPrintedPage,extractStatementPeriod,extractMid,extractMerchantName,detectMissingAndOrder,compareIdentity} from './pdf-validation.js';
pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.worker.min.mjs';
const state={files:[],results:[],currentScreen:'home'};
const titles={home:'Home','new-analysis':'New Analysis',validation:'Statement Validation',history:'History',settings:'Settings'};
const $=id=>document.getElementById(id);
const el={pdfInput:$('pdfInput'),dropZone:$('dropZone'),statementQueue:$('statementQueue'),emptyQueue:$('emptyQueue'),statementCount:$('statementCount'),totalSize:$('totalSize'),clearQueue:$('clearQueue'),continueButton:$('continueButton'),fileStatus:$('fileStatus'),validationFiles:$('validationFiles'),validationLoaded:$('validationLoaded'),screenTitle:$('screenTitle')};
function navigate(id){if(!$(id))return;document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('active',s.id===id));document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.screen===id));state.currentScreen=id;el.screenTitle.textContent=titles[id]||'ClearCost AI';window.scrollTo({top:0,behavior:'smooth'});}
function formatBytes(bytes){if(!bytes)return'0 KB';const u=['B','KB','MB','GB'];const i=Math.min(Math.floor(Math.log(bytes)/Math.log(1024)),u.length-1);return`${(bytes/1024**i).toFixed(i?2:0)} ${u[i]}`;}
const fileKey=f=>`${f.name}-${f.size}-${f.lastModified}`;
function addFiles(list){for(const file of Array.from(list).filter(f=>f.type==='application/pdf'||f.name.toLowerCase().endsWith('.pdf'))){if(!state.files.some(x=>fileKey(x)===fileKey(file)))state.files.push(file);}state.results=[];renderQueue();}
function renderQueue(){el.statementQueue.innerHTML='';for(const file of state.files){const card=document.createElement('article');card.className='file-card';card.innerHTML=`<div><strong></strong><small>${formatBytes(file.size)} · Ready for validation</small></div><button class="remove-file" type="button" aria-label="Remove file">×</button>`;card.querySelector('strong').textContent=file.name;card.querySelector('button').onclick=()=>{state.files=state.files.filter(f=>fileKey(f)!==fileKey(file));state.results=[];renderQueue();};el.statementQueue.append(card);}el.statementCount.textContent=state.files.length;el.totalSize.textContent=formatBytes(state.files.reduce((s,f)=>s+f.size,0));el.emptyQueue.hidden=!!state.files.length;el.clearQueue.disabled=!state.files.length;el.continueButton.disabled=!state.files.length;el.fileStatus.textContent=state.files.length?`${state.files.length} PDF file${state.files.length===1?'':'s'} loaded`:'Waiting for statement selection';}
function setText(id,text){$(id).textContent=text;}
async function inspectPage(page,index){const textContent=await page.getTextContent();const text=textContent.items.map(item=>item.str).join('\n').trim();const hasText=text.replace(/\s/g,'').length>=20;const printed=extractPrintedPage(text);const viewport=page.getViewport({scale:1});const rotation=((viewport.rotation%360)+360)%360;const charCount=text.replace(/\s/g,'').length;const readable=hasText?charCount>=35:true;const fingerprint=stableHash(text.replace(/\s+/g,' ').trim().toLowerCase()||`image-page-${index}-${viewport.width}x${viewport.height}`);return {index,text,hasText,ocrRequired:!hasText,printed,rotation,readable,charCount,fingerprint};}
async function inspectFile(file){const bytes=new Uint8Array(await file.arrayBuffer());const pdf=await pdfjsLib.getDocument({data:bytes}).promise;const pages=[];for(let i=1;i<=pdf.numPages;i++)pages.push(await inspectPage(await pdf.getPage(i),i));const joined=pages.map(p=>p.text).join('\n');const duplicates=[];const hashes=new Map();for(const p of pages){if(hashes.has(p.fingerprint))duplicates.push([hashes.get(p.fingerprint),p.index]);else hashes.set(p.fingerprint,p.index);}const sequence=detectMissingAndOrder(pages.map(p=>p.printed));return {name:file.name,pageCount:pdf.numPages,pages,period:extractStatementPeriod(joined),mid:extractMid(joined),merchant:extractMerchantName(joined),duplicates,missing:sequence.missing,outOfOrder:sequence.outOfOrder,expectedTotal:sequence.expectedTotal};}
function summarize(){const allPages=state.results.flatMap(r=>r.pages);const identity=compareIdentity(state.results);const total=allPages.length,ocr=allPages.filter(p=>p.ocrRequired).length,rotated=allPages.filter(p=>p.rotation!==0).map(p=>p.index),unreadable=allPages.filter(p=>!p.readable).map(p=>p.index);const missing=state.results.flatMap(r=>r.missing.map(p=>`${r.name}: ${p}`));const duplicates=state.results.flatMap(r=>r.duplicates.map(([a,b])=>`${r.name}: ${a}/${b}`));const order=state.results.flatMap(r=>r.outOfOrder.map(p=>`${r.name}: ${p}`));setText('pageCountStatus',`${total} page${total===1?'':'s'}`);setText('textLayerStatus',`${total-ocr} of ${total} pages`);setText('ocrRequiredStatus',ocr?`${ocr} page${ocr===1?'':'s'}`:'No');setText('periodStatus',identity.periodMatch?(identity.periods.length?'Match':'Not detected'):'Mismatch');setText('merchantStatus',identity.midMatch&&identity.merchantMatch?((identity.mids.length||identity.merchants.length)?'Match':'Not detected'):'Mismatch');setText('missingStatus',missing.length?missing.join('; '):'None detected');setText('duplicateStatus',duplicates.length?duplicates.join('; '):'None detected');setText('rotationStatus',rotated.length?`${rotated.length} page(s)`:'None');setText('readabilityStatus',unreadable.length?`${unreadable.length} page(s) need review`:'Pass');setText('orderStatus',order.length?order.join('; '):'Pass');const errors=[!identity.periodMatch,!identity.midMatch,!identity.merchantMatch,missing.length,order.length].filter(Boolean).length;const warnings=[ocr,duplicates.length,rotated.length,unreadable.length,!identity.periods.length,!identity.mids.length&&!identity.merchants.length].filter(Boolean).length;const notice=$('validationNotice');notice.className=`notice ${errors?'error':warnings?'warning':'ok'}`;notice.innerHTML=errors?`<strong>Validation failed</strong><p>${errors} blocking issue(s) found. Fee analysis must not continue until resolved.</p>`:warnings?`<strong>Review required</strong><p>No blocking identity or page-sequence mismatch was found, but ${warnings} warning category(s) require review.</p>`:`<strong>Validation passed</strong><p>Document integrity checks passed. The statements are ready for the next extraction stage.</p>`;setText('pageValidationStatus',errors?'Failed':warnings?'Review required':'Passed');setText('identityStatus',identity.periodMatch&&identity.midMatch&&identity.merchantMatch?'Passed':'Failed');setText('ocrStatus',ocr?`${ocr} page(s) require OCR`:'Text layer available');}
function renderValidation(){el.validationFiles.innerHTML='';el.validationLoaded.textContent=state.results.length;for(const r of state.results){const card=document.createElement('article');card.className='file-card';const issues=r.missing.length+r.duplicates.length+r.outOfOrder.length+r.pages.filter(p=>p.rotation!==0||!p.readable).length;card.innerHTML=`<div><strong></strong><small>${r.pageCount} page(s) · ${r.pages.filter(p=>p.ocrRequired).length} OCR-required · ${issues?`${issues} issue(s)`:'validated'}</small></div><span aria-hidden="true">${issues?'⚠':'✓'}</span>`;card.querySelector('strong').textContent=r.name;el.validationFiles.append(card);}summarize();}
async function validate(){el.continueButton.disabled=true;el.continueButton.textContent='Validating…';setText('pageValidationStatus','Reading PDF pages');try{state.results=[];for(const file of state.files)state.results.push(await inspectFile(file));renderValidation();navigate('validation');}catch(error){const notice=$('validationNotice');notice.className='notice error';notice.innerHTML=`<strong>PDF validation error</strong><p>${String(error.message||error)}</p>`;navigate('validation');}finally{el.continueButton.disabled=!state.files.length;el.continueButton.textContent='Validate Statements';}}
document.addEventListener('click',e=>{const b=e.target.closest('[data-screen]');if(b)navigate(b.dataset.screen);});el.pdfInput.addEventListener('change',e=>addFiles(e.target.files));el.clearQueue.onclick=()=>{state.files=[];state.results=[];el.pdfInput.value='';renderQueue();};el.continueButton.onclick=validate;['dragenter','dragover'].forEach(n=>el.dropZone.addEventListener(n,e=>{e.preventDefault();el.dropZone.classList.add('dragover');}));['dragleave','drop'].forEach(n=>el.dropZone.addEventListener(n,e=>{e.preventDefault();el.dropZone.classList.remove('dragover');}));el.dropZone.addEventListener('drop',e=>addFiles(e.dataTransfer.files));renderQueue();navigate('home');
